name: test-format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          deps: "true"

      - name: Check formatting
        run: just check-formatted
